# Налаштування бази даних H2 в пам'яті
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Тимчасово дозволяємо доступ до сторінок без логіну (для простоти MVC)
spring.security.user.name=user
spring.security.user.password=password